spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

# actuator
management:
  server:
    port: 8081
